services:
  - type: web
    name: ishraq-api
    env: node
    buildCommand: npm run build:api
    startCommand: npm --workspace=apps/api run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
